# Generated by Django 4.1.2 on 2022-11-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client',
            field=models.CharField(max_length=32, null=True, verbose_name='Гость'),
        ),
    ]
